server:
  port: 9002
  servlet:
    context-path: /user
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:
    host: localhost
  rabbitmq:
    host: localhost
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #注册ip地址
        enabled: true
        register: true # 注册自身到consul
        deregister: true # 服务停止时取消注册
        service-name: ${spring.application.name} # 注册到 Consul 的服务名，默认为 `spring.application.name` 配置项
        health-check-path: /user/actuator/health # 健康检查的接口，默认为 /actuator/health，由 Spring Boot Actuator 提供
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 20000
mybatis:
  configuration:
    map-underscore-to-camel-case: true #该配置项就是指将带有下划线的表字段映射为驼峰格式的实体类属性。