spring:
  application:
    name: gateway-user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #注册ip地址
        enabled: true
        register: true # 注册自身到consul
        deregister: true # 服务停止时取消注册
        service-name: ${spring.application.name} # 注册到 Consul 的服务名，默认为 `spring.application.name` 配置项
        health-check-path: /actuator/health # 健康检查的接口，默认为 /actuator/health，由 Spring Boot Actuator 提供
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          #用户微服务
        - id: user_route
          uri: lb://user
          predicates:
            - Path=/user/**,/address/**,/areas/**,/cities/**,/provinces/**
          #filters:
            #- PrefixPath=/brand #让真实请求地址增加前缀
            #- StripPrefix=1
          #认证微服务
        - id: user_oauth
          uri: lb://user-auth
          predicates:
            - Path=/oauth/**
  redis:
    host: localhost
server:
  port: 9000
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true